# site properties and page defaults
title: Lingnan Visual Cognition Lab
subtitle: Department of Psychology, Lingnan University
description: vision, facial recognition, attention, decision-making, modeling
header: images/Venice.jpg
footer: images/background.jpg


# site social media and other links
links:
  email: visual_cognition_lab@ln.edu.hk
  orcid: 0000-0002-7248-0301
  google-scholar: MyN21LIAAAAJ&hl=en
  github: vcl-ln
  # twitter: vcl-ln
  # youtube: vcl-ln

# base directory where site is hosted
header: images/Venice.jpg
footer: images/background.png
baseurl: /vcl-ln.github.io

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
